const mtgSpiderManSet = [
  {
    name: 'Spider-Man, Friendly Neighborhood',
    manaCost: '1UR',
    type: 'Legendary Creature — Spider Human',
    rarity: 'Rare',
    text: 'Vigilance. Whenever Spider-Man, Friendly Neighborhood deals combat damage to a player, create a 1/1 Spider creature token with reach.',
    power: '3',
    toughness: '3',
    set: 'Spider-Man Set',
  },
  {
    name: 'Spider-Man, Web-Slinger',
    manaCost: '2UR',
    type: 'Legendary Creature — Spider Human',
    rarity: 'Mythic Rare',
    text: 'Flash. When Spider-Man, Web-Slinger enters the battlefield, return target spell or creature to its owner\'s hand. Whenever you cast a creature spell, you may have it gain reach until end of turn.',
    power: '4',
    toughness: '4',
    set: 'Spider-Man Set',
  },
  {
    name: 'Daily Bugle Bailiff',
    manaCost: '1W',
    type: 'Creature — Human Soldier',
    rarity: 'Uncommon',
    text: 'Whenever another creature enters the battlefield under your control, you may tap target creature an opponent controls. If you do, that creature doesn\'t untap during its controller\'s next untap step.',
    power: '2',
    toughness: '2',
    set: 'Spider-Man Set',
  },
  {
    name: 'Aunt May\'s Encouragement',
    manaCost: '1W',
    type: 'Enchantment',
    rarity: 'Uncommon',
    text: 'Whenever a creature you control attacks, you may gain 1 life. If you do, put a +1/+1 counter on target attacking creature you control.',
    set: 'Spider-Man Set',
  },
  {
    name: 'Web of Justice',
    manaCost: '1U',
    type: 'Instant',
    rarity: 'Rare',
    text: 'Counter target spell unless its controller pays 2. Scry 1.',
    set: 'Spider-Man Set',
  },
  {
    name: 'Kingpin of Crime',
    manaCost: '2BB',
    type: 'Legendary Creature — Human Rogue',
    rarity: 'Rare',
    text: 'Whenever Kingpin of Crime deals combat damage to a player, that player discards a card and you draw a card.',
    power: '3',
    toughness: '3',
    set: 'Spider-Man Set',
  },
  {
    name: 'Daily Bugle Scoop',
    manaCost: '2U',
    type: 'Sorcery',
    rarity: 'Uncommon',
    text: 'Draw two cards, then discard a card unless you control a creature named Spider-Man, Friendly Neighborhood.',
    set: 'Spider-Man Set',
  },
  {
    name: 'Symbiote Strike',
    manaCost: '1B',
    type: 'Instant',
    rarity: 'Uncommon',
    text: 'Target creature gets +2/+1 and deathtouch until end of turn. If that creature is named Spider-Man, Friendly Neighborhood, it also gains lifelink.',
    set: 'Spider-Man Set',
  },
];
